<?php
function auth_setting($conn,$key,$default=''){
    return settings_get($conn,$key,$default);
}
function auth_absolute_url($path=''){
    global $base_url;$https=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')||(($_SERVER['HTTP_X_FORWARDED_PROTO']??'')==='https');$scheme=$https?'https':'http';$host=$_SERVER['HTTP_HOST']??'localhost';return $scheme.'://'.$host.rtrim($base_url,'/').'/'.ltrim($path,'/');
}
function auth_google_configured($conn){return trim(auth_setting($conn,'google_client_id'))!==''&&trim(auth_setting($conn,'google_client_secret'))!=='';}
function auth_google_redirect_uri($conn){$stored=trim(auth_setting($conn,'google_redirect_uri'));return $stored!==''?$stored:auth_absolute_url('dang-nhap-google/callback');}
function auth_google_start_url($conn){
    if(!auth_google_configured($conn))return '';$state=bin2hex(random_bytes(24));$_SESSION['google_oauth_state']=$state;$_SESSION['google_oauth_started_at']=time();return 'https://accounts.google.com/o/oauth2/v2/auth?'.http_build_query(['client_id'=>trim(auth_setting($conn,'google_client_id')),'redirect_uri'=>auth_google_redirect_uri($conn),'response_type'=>'code','scope'=>'openid email profile','state'=>$state,'prompt'=>'select_account','include_granted_scopes'=>'true']);
}
function auth_http_post($url,$data){
    if(!function_exists('curl_init'))return null;$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query($data),CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>20,CURLOPT_CONNECTTIMEOUT=>10,CURLOPT_HTTPHEADER=>['Content-Type: application/x-www-form-urlencoded','Accept: application/json']]);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if($raw===false||$status<200||$status>=300)return null;$json=json_decode((string)$raw,true);return is_array($json)?$json:null;
}
function auth_google_profile($conn,$code,$state){
    if($code===''||$state===''||empty($_SESSION['google_oauth_state'])||!hash_equals((string)$_SESSION['google_oauth_state'],$state))return null;if(!empty($_SESSION['google_oauth_started_at'])&&time()-(int)$_SESSION['google_oauth_started_at']>900)return null;unset($_SESSION['google_oauth_state'],$_SESSION['google_oauth_started_at']);$token=auth_http_post('https://oauth2.googleapis.com/token',['code'=>$code,'client_id'=>trim(auth_setting($conn,'google_client_id')),'client_secret'=>trim(auth_setting($conn,'google_client_secret')),'redirect_uri'=>auth_google_redirect_uri($conn),'grant_type'=>'authorization_code']);if(!$token||empty($token['access_token'])||!function_exists('curl_init'))return null;$ch=curl_init('https://openidconnect.googleapis.com/v1/userinfo');curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$token['access_token'],'Accept: application/json'],CURLOPT_TIMEOUT=>20,CURLOPT_CONNECTTIMEOUT=>10]);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if($raw===false||$status<200||$status>=300)return null;$data=json_decode((string)$raw,true);if(!is_array($data)||empty($data['sub'])||empty($data['email']))return null;if(isset($data['email_verified'])&&!$data['email_verified'])return null;return $data;
}
function auth_smtp_expect($socket,$codes){$response='';while(($line=fgets($socket,515))!==false){$response.=$line;if(strlen($line)<4||$line[3]===' ')break;}$code=(int)substr($response,0,3);return in_array($code,$codes,true);}
function auth_smtp_command($socket,$command,$codes){if(@fwrite($socket,$command."\r\n")===false)return false;return auth_smtp_expect($socket,$codes);}
function auth_send_mail($conn,$to,$subject,$html){
    $host=trim(auth_setting($conn,'mail_host','smtp.gmail.com'));$port=(int)auth_setting($conn,'mail_port','587');$user=trim(auth_setting($conn,'mail_username'));$pass=(string)auth_setting($conn,'mail_password');$encryption=strtolower(trim(auth_setting($conn,'mail_encryption','tls')));$from=trim(auth_setting($conn,'mail_from_address',$user));$name=trim(auth_setting($conn,'mail_from_name','NovaTech'));if(!filter_var($to,FILTER_VALIDATE_EMAIL)||$host===''||$port<1||!filter_var($user,FILTER_VALIDATE_EMAIL)||$pass===''||!filter_var($from,FILTER_VALIDATE_EMAIL))return false;if(!in_array($encryption,['tls','ssl','none'],true))$encryption='tls';$target=$encryption==='ssl'?"ssl://{$host}:{$port}":"tcp://{$host}:{$port}";$context=stream_context_create(['ssl'=>['verify_peer'=>true,'verify_peer_name'=>true,'allow_self_signed'=>false]]);$socket=@stream_socket_client($target,$errno,$errstr,20,STREAM_CLIENT_CONNECT,$context);if(!$socket)return false;stream_set_timeout($socket,20);$helo=$_SERVER['SERVER_NAME']??'localhost';if(!auth_smtp_expect($socket,[220])||!auth_smtp_command($socket,'EHLO '.$helo,[250])){fclose($socket);return false;}if($encryption==='tls'){if(!auth_smtp_command($socket,'STARTTLS',[220])||!@stream_socket_enable_crypto($socket,true,STREAM_CRYPTO_METHOD_TLS_CLIENT)||!auth_smtp_command($socket,'EHLO '.$helo,[250])){fclose($socket);return false;}}if(!auth_smtp_command($socket,'AUTH LOGIN',[334])||!auth_smtp_command($socket,base64_encode($user),[334])||!auth_smtp_command($socket,base64_encode($pass),[235])||!auth_smtp_command($socket,"MAIL FROM:<{$from}>",[250])||!auth_smtp_command($socket,"RCPT TO:<{$to}>",[250,251])||!auth_smtp_command($socket,'DATA',[354])){fclose($socket);return false;}$encode=function($v){return '=?UTF-8?B?'.base64_encode($v).'?=';};$headers=['From: '.$encode($name)." <{$from}>",'To: <'.$to.'>','Subject: '.$encode($subject),'MIME-Version: 1.0','Content-Type: text/html; charset=UTF-8','Content-Transfer-Encoding: 8bit','Date: '.date(DATE_RFC2822)];$body=str_replace(["\r\n","\r"],"\n",$html);$body=preg_replace('/^\./m','..',$body);fwrite($socket,implode("\r\n",$headers)."\r\n\r\n".str_replace("\n","\r\n",$body)."\r\n.\r\n");$ok=auth_smtp_expect($socket,[250]);auth_smtp_command($socket,'QUIT',[221]);fclose($socket);return $ok;
}
function auth_send_reset_otp($conn,$user,$otp){$site=auth_setting($conn,'site_name','NovaTech');$subject='Mã xác nhận đổi mật khẩu - '.$site;$html='<div style="font-family:Arial,sans-serif;max-width:560px;margin:auto;color:#403832"><h2 style="color:#6f513c">'.$site.'</h2><p>Xin chào '.htmlspecialchars($user['fullname']).',</p><p>Mã OTP để đặt lại mật khẩu của bạn là:</p><div style="font-size:30px;font-weight:700;letter-spacing:6px;padding:18px;background:#f7f3ee;text-align:center;border-radius:10px">'.$otp.'</div><p>Mã có hiệu lực trong 15 phút. Nếu bạn không yêu cầu đổi mật khẩu, hãy bỏ qua email này.</p></div>';return auth_send_mail($conn,$user['email'],$subject,$html);}
?>
